services:
  transcribe:
    build: .
    container_name: niri-transcribe
    user: "1000:29"  # user:audio group for /dev/snd access
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PIPEWIRE_RUNTIME_DIR=/tmp
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AUDIO_DEVICE=${AUDIO_DEVICE}
      - VAD_THRESHOLD=${VAD_THRESHOLD}
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER}
      - DEBUG=${DEBUG}
    volumes:
      # PipeWire socket (read/write for device access)
      - /run/user/1000/pipewire-0:/tmp/pipewire-0:rw
      - /run/user/1000/pipewire-0-manager:/tmp/pipewire-0-manager:rw
      # PulseAudio fallback (read/write for device access)
      - /run/user/1000/pulse:/tmp/pulse:rw
      # Wayland socket for text injection
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}:rw
      # Config directory
      - ./config:/app/config:ro
    devices:
      # ALSA fallback
      - /dev/snd:/dev/snd
    restart: unless-stopped
    networks:
      - transcribe-net

networks:
  transcribe-net:
    driver: bridge