version: '3.8'

services:
  transcribe:
    build: .
    container_name: niri-transcribe
    user: "1000:1000"
    ports:
      - "3000:3000"
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - PULSE_SERVER=/tmp/pulse/native
      - NODE_ENV=production
    volumes:
      # PipeWire socket
      - /run/user/1000/pipewire-0:/tmp/pipewire-0:ro
      # PulseAudio fallback
      - /run/user/1000/pulse:/tmp/pulse:ro
      # Wayland socket
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}:rw
      # Config directory
      - ./config:/app/config:ro
    devices:
      # ALSA fallback
      - /dev/snd:/dev/snd
    restart: unless-stopped
    networks:
      - transcribe-net

networks:
  transcribe-net:
    driver: bridge